---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: "local-path"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.96.14
    path: "/mnt/data/nexus-data"
  claimRef:
    namespace: nexus
    name: nexus-storage
---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-storage
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: "nexus-pv"
---
